version: '3'
services:
  wind-fall-api:
    image: ${DOCKER_USERNAME}/wind-fall-server:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/logs
    networks:
      - windfall-net

networks:
  windfall-net:
    external: true