spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #  elasticsearch:
#    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  kakao:
    client:
      id: ${REST_API_KAKAO}
      secret: ${CLIENT_SECRET_KAKAO}
    redirect:
      uri: ${REDIRECT_URI_KAKAO}

  naver:
    client:
      id: ${CLIENT_ID_NAVER}
    redirect:
      uri: ${REDIRECT_URI_NAVER}

  google:
    client:
      id: ${CLIENT_ID_GOOGLE}
    redirect:
      uri: ${REDIRECT_URI_GOOGLE}

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.backend: DEBUG

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

custom:
  jwt:
    expireSecondsAccessToken: 3600 # 1시간
    expireSecondsRefreshToken: 604800 # 7일
    secretPattern: ${SECRET_PATTERN}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  seed:
    enabled: false   # 기본은 false
    reset: false     # true면 전체 삭제 후 재삽입
    marker-email: seed_admin@windfall.local

aws:
  s3:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${BUCKET_NAME}
    baseUrl: ${S3_BASE_URL}